from fastapi import APIRouter

from app.assistant.ollama_client import ask_ollama, is_ollama_available
from app.assistant.schema_context import SCHEMA_CONTEXT
from app.assistant.sql_guard import is_safe_sql, sanitize_sql
from app.assistant.templates import match_template
from app.core.logging import logger
from app.data.duckdb_repo import DuckDBRepo
from app.models.api_models import AssistantRequest, AssistantResponse

router = APIRouter(tags=["assistant"])


@router.post("/assistant/ask", response_model=AssistantResponse)
def ask_assistant(req: AssistantRequest) -> AssistantResponse:
    warnings = []
    template = match_template(req.question)

    if template:
        sql = template["sql"]
        explanation = template["explanation"]
    else:
        if not is_ollama_available():
            return AssistantResponse(
                question=req.question,
                answer="No matching query template found and Ollama is not available. Try: 'Which asset had the highest volatility?', 'Show me stale price breaks', 'What changed in portfolio NAV?', or 'Which asset had the largest daily return?'",
                query_used="none",
                rows=[],
                warnings=["Ollama not running. Install Ollama and pull a model (e.g., 'ollama pull qwen3:4b') for AI-powered answers."],
            )

        ollama_sql = ask_ollama(
            question=f"Generate a read-only SELECT SQL query for this question: {req.question}\n\nSchema:\n{SCHEMA_CONTEXT}\n\nReturn ONLY the SQL query, nothing else.",
            system_prompt="You are a SQL assistant. Generate only SELECT queries. Never generate INSERT, UPDATE, DELETE, DROP, or any destructive statements.",
        )

        if not ollama_sql:
            return AssistantResponse(
                question=req.question,
                answer="Could not reach the LLM assistant. Please try a predefined question or ensure Ollama is running.",
                query_used="none",
                rows=[],
                warnings=["Ollama request failed"],
            )

        sql = ollama_sql.strip()
        explanation = "Generated by LLM"

    safe, reason = is_safe_sql(sql)
    if not safe:
        warnings.append(f"SQL safety check: {reason}")
        return AssistantResponse(
            question=req.question,
            answer=f"Query was blocked for safety: {reason}",
            query_used=sql,
            rows=[],
            warnings=warnings,
        )

    sql = sanitize_sql(sql)

    try:
        with DuckDBRepo() as repo:
            rows = repo.query(sql)
    except Exception as e:
        logger.error(f"Assistant query failed: {e}")
        return AssistantResponse(
            question=req.question,
            answer=f"Query execution failed: {e}",
            query_used=sql,
            rows=[],
            warnings=[f"Query error: {e}"],
        )

    if template:
        answer = f"{explanation}\n\nFound {len(rows)} rows."
    else:
        answer = f"Query returned {len(rows)} rows.\n\n{explanation}"

    return AssistantResponse(
        question=req.question,
        answer=answer,
        query_used=sql,
        rows=rows,
        warnings=warnings,
    )
